import React from 'react';
import {
  FormControlLabel,
  Checkbox,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  FormHelperText,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button
} from '@mui/material';
import { useState, useEffect } from 'react';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider, DatePicker } from '@mui/x-date-pickers';
import ActionButton from 'utils/ActionButton';
import ClearIcon from '@mui/icons-material/Clear';
import SearchIcon from '@mui/icons-material/Search';
import dayjs from 'dayjs';
import apiCalls from 'apicall';
import { showToast } from 'utils/toast-component';
import CommonReportTable from 'utils/CommonReportTable';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { getAllActiveBranches } from 'utils/CommonFunctions';
import CircularProgress from '@mui/material/CircularProgress';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
const ArOutstanding = () => {
  const [listViewData, setListViewData] = useState([]);
  const [userName] = useState(localStorage.getItem('userName'));
  const [orgId, setOrgId] = useState(localStorage.getItem('orgId'));
  const [finYear, setFinYear] = useState(localStorage.getItem('finYear'));
  const [isLoading, setIsLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [partyNameList, setpartyNameList] = useState([]);
  const [fieldErrors, setFieldErrors] = useState({});
  const [rowData, setRowData] = useState([]);
  const [branchList, setbranchList] = useState([]);
  const [listView, setListView] = useState(false);
  const [selectedSections, setSelectedSections] = useState({
    partyName: false,
    date: true,
    slab: false,
    branch: false,
    dueDate: false
  });
  const [headerFields, setHeaderFields] = useState([]);
  const capitalizeHeader = (text) => text.replace(/\b\w/g, (char) => char.toUpperCase());

  const handleChange = (e) => {
    const { name, checked } = e.target;
    setSelectedSections((prevState) => ({
      ...prevState,
      [name]: checked
    }));

    if (name === 'date' && checked) {
      const today = dayjs().format('DD-MM-YYYY');
      setFormData((prev) => ({
        ...prev,
        date: today
      }));
      setFieldErrors((prev) => ({
        ...prev,
        date: ''
      }));
    }
  };

  const [formData, setFormData] = useState({
    partyName: 'All',
    date: dayjs().format('DD-MM-YYYY'),
    dueDate: null,
    branch: 'All',
    slab1: '',
    slab2: '',
    slab3: '',
    slab4: '',
    slab5: '',
    slab6: ''
  });

  const handleDownloadExcel = async ({ logo }) => {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('AR OutStanding Report');

    // ====== LOGO SECTION ======
    sheet.mergeCells('A1:B5');
    if (logo) {
      try {
        const base64Data = logo.split(',')[1] || logo;
        if (base64Data.length >= 100) {
          const extension = logo.includes('jpeg') ? 'jpeg' : 'png';
          const imageId = workbook.addImage({
            base64: base64Data,
            extension,
            type: 'image' // Ensure image type is specified
          });
          sheet.addImage(imageId, {
            tl: { col: 0, row: 0 },
            ext: { width: 120, height: 80 }
          });
        }
      } catch (err) {
        console.error('Error adding logo:', err);
      }
    }

    // ====== TITLE ======
    sheet.mergeCells('C1:H2');
    const titleCell = sheet.getCell('C1');
    titleCell.value = 'AR_Outstanding_Report';
    titleCell.font = {
      size: 18,
      bold: true,
      color: { argb: 'FF34449B' }
    };
    titleCell.alignment = {
      vertical: 'middle',
      horizontal: 'center'
    };

    // ====== HEADER INFO ======
    const headerInfo = [
      ...headerFields,
      { label: 'Generated By', value: localStorage.getItem('userName') || 'Admin' },
      { label: 'Generated On', value: dayjs().format('DD-MM-YYYY HH:mm') }
    ];

    for (let i = 0; i < headerInfo.length; i += 2) {
      const rowIndex = i / 2 + 3;
      const row = sheet.getRow(rowIndex);

      const labelCell1 = row.getCell(3);
      const valueCell1 = row.getCell(4);
      labelCell1.value = headerInfo[i].label + ':';
      labelCell1.font = { bold: true };
      valueCell1.value = headerInfo[i].value;

      if (headerInfo[i + 1]) {
        const labelCell2 = row.getCell(6);
        const valueCell2 = row.getCell(7);
        labelCell2.value = headerInfo[i + 1].label + ':';
        labelCell2.font = { bold: true };
        valueCell2.value = headerInfo[i + 1].value;
      }
    }

    // ====== COLUMN HEADERS ======
    // const headers = ['Branch', 'Customer', 'Credit Days', 'Credit Limit', 'Outstanding', 'Unadjusted', 'Total Due'];
    // const headerRow = sheet.addRow(headers);
    // headerRow.height = 20;
    // headerRow.font = {
    //   bold: true,
    //   color: { argb: 'FFFFFFFF' }
    // };
    // headerRow.fill = {
    //   type: 'pattern',
    //   pattern: 'solid',
    //   fgColor: { argb: 'FF34449B' }
    // };
    // headerRow.alignment = {
    //   horizontal: 'center',
    //   vertical: 'middle'
    // };

    // headerRow.eachCell((cell) => {
    //   cell.border = {
    //     top: { style: 'thin' },
    //     left: { style: 'thin' },
    //     bottom: { style: 'thin' },
    //     right: { style: 'thin' }
    //   };
    // });
    const headers = ['Branch', 'Customer', 'Credit Days', 'Credit Limit', 'Outstanding', 'Unadjusted', 'Total Due'];
    const headerRow = sheet.addRow(headers);
    headerRow.height = 20;
    sheet.views = [
      { state: 'frozen', ySplit: sheet.rowCount } // This will freeze everything above this row
    ];

    headerRow.eachCell((cell) => {
      cell.font = {
        bold: true,
        color: { argb: 'FFFFFFFF' }
      };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF34449B' }
      };
      cell.alignment = {
        horizontal: 'center',
        vertical: 'middle'
      };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // ====== DATA ROWS ======
    rowData.forEach((item) => {
      const vendorParts = [item.subledgerCode || '', item.subledgerName || '', item.currency || ''].filter(Boolean).join(' - ');

      const vendorDisplay = item.subledgerName?.toLowerCase().startsWith('total') ? item.subledgerName : vendorParts;
      const isTotalRow = item.subledgerName?.trim().toLowerCase() === 'total';
      const row = sheet.addRow([
        item.branch || '',
        vendorDisplay || '',
        typeof item.creditDays === 'number' ? item.creditDays : Number(item.creditDays) || '',
        typeof item.creditLimit === 'number' ? item.creditLimit : Number(item.creditLimit) || '',
        typeof item.outstanding === 'number' ? item.outstanding : Number(item.outstanding) || '',
        typeof item.unadjusted === 'number' ? item.unadjusted : Number(item.unadjusted) || '',
        typeof item.totaldue === 'number' ? item.totaldue : Number(item.totaldue) || ''
      ]);

      // Format numeric columns
      [4, 5, 6, 7].forEach((colIndex) => {
        const cell = row.getCell(colIndex);
        if (typeof cell.value === 'number') {
          cell.numFmt = '#,##0.00';
          cell.alignment = { horizontal: 'right' };
        }
      });

      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        if (isTotalRow) {
          cell.font = { bold: true };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFD9D9D9' }
          };
        }
      });
    });

    // ====== COLUMN WIDTHS ======
    sheet.columns = [
      { width: 20 }, // Branch
      { width: 40 }, // Vendor
      { width: 12 }, // Credit Days
      { width: 15 }, // Credit Limit
      { width: 15 }, // Outstanding
      { width: 15 }, // Unadjusted
      { width: 15 } // Total Due
    ];

    // ====== EXPORT FILE ======
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    saveAs(blob, `AR_Outstanding_Report_${dayjs().format('YYYYMMDD_HHmmss')}.xlsx`);
  };

  const handleDateChange = (field, date) => {
    const formattedDate = date ? dayjs(date).format('DD-MM-YYYY') : null;
    setFormData((prevData) => ({ ...prevData, [field]: formattedDate }));
    setFieldErrors((prev) => ({ ...prev, date: '' }));
  };

  const allClearData = () => {
    setFormData({ partyName: 'All', date: dayjs().format('DD-MM-YYYY'), branch: 'All' });
    setSelectedSections({ partyName: false, date: true });
    setFieldErrors({});
    setListView(false);
    setRowData([]);
  };

  useEffect(() => {
    getpartyName();
    getAllBranches();
    getCompanyDetails();
  }, []);

  const getAllBranches = async () => {
    try {
      const branchData = await getAllActiveBranches(orgId);
      setbranchList(branchData);
    } catch (error) {
      console.error('Error fetching country data:', error);
    }
  };

  const getpartyName = async () => {
    try {
      const response = await apiCalls('get', `/taxInvoice/getPartyNameByPartyType?orgId=${orgId}&partyType=customer`);
      setpartyNameList(response.paramObjectsMap.partyMasterVO);
    } catch (error) {
      console.error('Error fetching gate passes:', error);
    }
  };

  const handleSelectPartyName = (e) => {
    const value = e.target.value;
    if (value === 'All') {
      setFormData((prevData) => ({
        ...prevData,
        partyName: 'All'
      }));
    } else {
      const selectedEmp = partyNameList.find((emp) => emp.partyName === value);

      if (selectedEmp) {
        setFormData((prevData) => ({
          ...prevData,
          partyName: selectedEmp.partyName
        }));
      }
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type } = e.target;

    setFieldErrors((prevErrors) => ({
      ...prevErrors,
      [name]: ''
    }));

    // if (name === 'branch') {
    //   if (value === 'All') {
    //     setFormData((prevData) => ({
    //       ...prevData,
    //       branch: 'All'
    //     }));
    //   }
    // }
    let inputValue = value;
    if (type === 'text' || type === 'textarea') {
      inputValue = value.toUpperCase();
    }
    setFormData((prevData) => ({ ...prevData, [name]: inputValue }));
  };

  const handleCheckboxChange = (event) => {
    const { name, checked } = event.target;
    setSelectedSections((prevState) => ({
      ...prevState,
      [name]: checked
    }));
  };

  const formatAmount = (value) => (value !== null && value !== undefined ? new Intl.NumberFormat('en-IN').format(value) : '');

  const reportColumns = [
    {
      accessorKey: 'branch',
      header: 'Branch',
      size: 80,
      Cell: ({ cell }) => <div style={{ textAlign: 'left', padding: '8px' }}>{cell.getValue() || ''}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      header: 'Customer',
      accessorKey: 'combinedCustomerInfo',
      size: 300,
      Cell: ({ row }) => {
        const code = row.original.subledgerCode || '';
        const name = row.original.subledgerName || '';
        const currency = row.original.currency || '';

        if (name.toLowerCase().startsWith('total')) {
          return <div style={{ textAlign: 'left', padding: '8px' }}>{name}</div>;
        }

        const parts = [code, name, currency].filter(Boolean);
        const displayValue = parts.join(' - ');

        return <div style={{ textAlign: 'left', padding: '8px' }}>{displayValue}</div>;
      },
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'creditDays',
      header: 'Credit Days',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'left', padding: '8px' }}>{cell.getValue() || ''}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'creditLimit',
      header: 'Credit Limit',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'outstanding',
      header: 'Outstanding',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'unadjusted',
      header: 'Unadjusted',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'totaldue',
      header: 'Total Due',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    }
  ];

  const handleSearch = async () => {
    if (selectedSections.date && !formData.date) {
      setFieldErrors((prevErrors) => ({
        ...prevErrors,
        date: selectedSections.date && !formData.date ? 'Date is required' : ''
      }));
      return;
    } else {
      setIsLoading(true);
      try {
        let response;
        if (formData.dueDate) {
          response = await apiCalls(
            'get',
            `/arapAdjustments/GetArapAdjustments?Asondate=${dayjs(formData.date).format('YYYY-DD-MM')}&branch=${formData.branch}&orgId=${orgId}&partyname=${formData.partyName}&pdate=${dayjs(formData.dueDate).format('YYYY-DD-MM')}`
          );
        } else {
          response = await apiCalls(
            'get',
            `/arapAdjustments/GetArapAdjustments?Asondate=${dayjs(formData.date).format('YYYY-DD-MM')}&partyname=${formData.partyName}&orgId=${orgId}&branch=${formData.branch}`
          );
        }
        if (response.status === true) {
          setRowData(response.paramObjectsMap.mapp);

          const headers = [
            // {
            //   // Combined date range value without a label
            //   value: formData.fromDate && formData.toDate
            //     ? `${dayjs(formData.fromDate).format('DD-MM-YYYY')} to ${dayjs(formData.toDate).format('DD-MM-YYYY')}`
            //     : ''
            // },
            {
              label: 'As On Date',
              value: formData.date
            },
            {
              label: 'Party Name',
              value: formData.partyName !== 'All' ? formData.partyName : 'All'
            },
            {
              label: 'Branch',
              value: formData.branch !== 'All' ? formData.branch : 'All'
            },
            { label: 'Due Date', value: formData.dueDate }
          ];

          setHeaderFields(headers);
          setIsLoading(false);
          setListView(true);
          setIsModalOpen(true);
        } else {
          showToast('error', response.paramObjectsMap.mapp.errorMessage || 'Report Fetch failed');
          setIsLoading(false);
        }
      } catch (error) {
        console.error('Error:', error);
        showToast('error', 'Report Fetch failed');
        setIsLoading(false);
      } finally {
        setIsLoading(false);
      }
    }
  };

  const tableOptions = {
    muiTablePaperProps: {
      sx: {
        border: '1px solid #e0e0e0',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
        borderRadius: '8px',
        overflow: 'hidden'
      }
    },
    muiTableContainerProps: {
      sx: { maxHeight: '70vh' }
    },
    muiTableBodyRowProps: ({ row }) => ({
      sx: {
        backgroundColor: row.index % 2 ? '#f9f9f9' : '#ffffff',
        '&:hover': { backgroundColor: '#f0f7ff' }
      }
    }),
    enableStickyHeader: true,
    muiTableProps: {
      sx: {
        borderCollapse: 'collapse',
        '& .MuiTableCell-root': {
          border: '1px solid #e0e0e0 !important'
        }
      }
    }
  };
  const getCompanyDetails = async () => {
    try {
      const response = await apiCalls('get', `commonmaster/company/${orgId}`);
      console.log('API Response:', response);
      setListViewData(response.paramObjectsMap.companyVO.reverse());
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  // PDF download
  const handleDownloadPdf = ({ logo, columns, data, fileName, userName, formData }) => {
    const doc = new jsPDF({ orientation: 'landscape' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();

    // 1) COMPANY LOGO (top-left)
    const logoBase64 = logo;
    const logoWidth = 30;
    const logoHeight = 23;
    const logoX = 10;
    const logoY = 10;
    if (logoBase64) {
      doc.addImage(logoBase64, 'PNG', logoX, logoY, logoWidth, logoHeight);
    }

    // 2) TITLE BOX
    const title = `${fileName}`;
    const textW = doc.getTextWidth(title);
    const padX = 10,
      boxH = 10,
      yTitle = 25;
    const boxW = textW + padX * 2,
      boxX = (pageW - boxW) / 2;
    doc
      .setFillColor('#e7ebeb')
      .roundedRect(boxX, yTitle - boxH + 3, boxW, boxH, 4, 4, 'F')
      .setTextColor('#34449B')
      .setFontSize(12)
      .text(title, pageW / 2, yTitle, { align: 'center' });

    // 4) FILTER METADATA
    const { date, partyName, branch, dueDate } = formData;
    doc.setFontSize(9);
    doc.setTextColor('#000000');
    doc.setFillColor(231, 235, 235);
    doc.roundedRect(2, 35, 292, 12, 2, 2, 'F');
    // Row 1: Labels (bold)
    doc.setFont(undefined, 'bold');
    doc.text('As on Date', 8, 40);
    doc.text('Party Name', 37, 40);
    doc.text('Branch', 125, 40);
    doc.text('Due Date', 178, 40);

    // Row 2: Values (normal)
    doc.setFont(undefined, 'normal');
    doc.text(dayjs(date).format('DD-MM-YYYY'), 8, 45);
    doc.text(partyName, 37, 45);
    doc.text(branch, 125, 45);
    doc.text(dueDate ? dayjs(dueDate).format('DD-MM-YYYY') : '', 178, 45);

    // 5) TABLE
    const headerLabels = columns.map((c) => c.header);
    const numericFields = columns
      .map((c) => c.accessorKey)
      .filter((k) => k && /(amount|outstanding|unAdjusted|totaldue|creditLimit|creditDays)/i.test(k));
    const body = data.map((row) =>
      columns.map((col) => {
        const key = col.accessorKey;
        const raw = key ? row[key] : '';
        if (key === 'combinedCustomerInfo') {
          const parts = [row.subledgerCode, row.subledgerName, row.currency].filter(Boolean);
          return parts.join(' - ');
        }
        if (key?.toLowerCase().includes('date')) {
          const d = dayjs(raw);
          return d.isValid() ? d.format('DD-MM-YYYY') : '-';
        }
        // if (!isNaN(raw) && raw !== null && raw !== '') {
        //   const number = Number(raw).toFixed(2);
        //   return number === 0 ? '' : number.toLocaleString('en-IN');
        // }
        // return raw ?? '';
        if (!isNaN(raw) && raw !== null && raw !== '') {
          const number = Number(raw);
          const formatted = number.toLocaleString('en-IN', {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
          });
          return number === 0 ? '' : formatted;
        }
        return raw ?? '';
      })
    );

    const columnStyles = {
      0: { cellWidth: 30 },
      1: { cellWidth: 100 },
      2: { cellWidth: 25 },
      3: { cellWidth: 25 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 },
      6: { cellWidth: 25 }
    };

    autoTable(doc, {
      startY: 50, // replace Fifty with a number like 60
      head: [headerLabels],
      body,
      styles: {
        fontSize: 8,
        cellPadding: 2,
        lineWidth: 0.1,
        lineColor: [220, 220, 220]
      },
      headStyles: {
        fillColor: [52, 68, 155],
        textColor: 255,
        halign: 'center'
      },
      bodyStyles: {
        halign: 'left'
      },
      bodyStyles: {
        halign: 'left'
      },
      theme: 'grid',
      margin: { left: 5, right: 5 },
      tableWidth: 'auto',
      columnStyles: columnStyles,
      didDrawPage: (data) => {
        doc.setFontSize(8).setTextColor('#555555');
        doc.text(`Generated On: ${dayjs().format('DD-MM-YYYY hh:mm A')}`, pageW - 15, pageH - 10, { align: 'right' });
        doc.text(`Generated By: ${userName}`, 15, pageH - 10, { align: 'left' });
      },
      didParseCell: (cellHookData) => {
        const { cell, column, section, row } = cellHookData;
        if (section === 'body') {
          // get the accessorKey for this column
          const key = columns[column.index].accessorKey;
          const rowData = data[row.index];

          // existing right-align logic
          if (numericFields.includes(key)) {
            cell.styles.halign = 'right';
          }
          if (rowData?.subledgerName?.trim().toLowerCase() === 'total') {
            cell.styles.fontStyle = 'bold';
            cell.styles.fillColor = [230, 230, 230];
          }
        }
      }

      // didParseCell: (cellHookData) => {
      //   const { cell, row, column, section } = cellHookData;
      //   const key = columns[column.index]?.accessorKey;

      //   // Right-align numeric fields
      //   if (section === 'body' && numericFields.includes(key)) {
      //     cell.styles.halign = 'right';
      //   }

      //   // Check if this is a "Total" row (any column)
      //   const isTotalRow = row.raw?.some?.((value) =>
      //     String(value || '')
      //       .toLowerCase()
      //       .includes('total')
      //   );

      //   // Apply styles to all cells in the row
      //   if (section === 'body' && isTotalRow) {
      //     cell.styles.fillColor = [230, 230, 230]; // light gray background
      //     cell.styles.fontStyle = 'bold';
      //     cell.styles.textColor = 0; // black text
      //   }
      // }
    });
    // 6) SAVE
    doc.save(`${fileName}_${dayjs().format('YYYYMMDD_HHmmss')}.pdf`);
  };

  return (
    <>
      <div className="card w-full p-6 bg-base-100 shadow-xl" style={{ padding: '20px', borderRadius: '10px' }}>
        <div className="row">
          <div className="row">
            <div className="col-md-2  mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.date} onChange={handleChange} name="date" color="secondary" />}
                label="Date"
              />
            </div>

            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.partyName} onChange={handleChange} name="partyName" color="secondary" />}
                label="Party Name"
              />
            </div>
            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.branch} onChange={handleCheckboxChange} name="branch" color="secondary" />}
                label="Branch"
              />
            </div>
            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.dueDate} onChange={handleCheckboxChange} name="dueDate" color="secondary" />}
                label="Due Date"
              />
            </div>
          </div>

          {selectedSections.date && (
            <div className="col-md-3">
              <FormControl fullWidth variant="filled" size="small">
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                  <DatePicker
                    label="As on Date"
                    format="DD-MM-YYYY"
                    onChange={(date) => handleDateChange('date', date)}
                    value={formData.date ? dayjs(formData.date, 'DD-MM-YYYY') : null}
                    slotProps={{
                      textField: {
                        size: 'small',
                        clearable: true,
                        error: !!fieldErrors.date,
                        helperText: fieldErrors.date
                      }
                    }}
                  />
                </LocalizationProvider>
              </FormControl>
            </div>
          )}

          {selectedSections.partyName && (
            <div className="col-md-3">
              <FormControl size="small" variant="outlined" fullWidth error={!!fieldErrors.partyName}>
                <InputLabel id="partyName-label">Party Name</InputLabel>
                <Select
                  labelId="partyName-label"
                  label="Party Name"
                  name="partyName"
                  value={formData.partyName}
                  onChange={handleSelectPartyName}
                  onBlur={() => {
                    if (!formData.partyName) {
                      setFieldErrors((prev) => ({
                        ...prev,
                        partyName: 'Party Name is required'
                      }));
                    }
                  }}
                >
                  <MenuItem value="All">All</MenuItem>
                  {partyNameList?.map((row) => (
                    <MenuItem key={row.id} value={row.partyName}>
                      {row.partyName}
                    </MenuItem>
                  ))}
                </Select>
                {fieldErrors.partyName && <FormHelperText>{fieldErrors.partyName}</FormHelperText>}
              </FormControl>
            </div>
          )}

          {selectedSections.branch && (
            <div className="col-md-3">
              <FormControl size="small" variant="outlined" fullWidth error={!!fieldErrors.branch}>
                <InputLabel id="branch-label">Branch</InputLabel>
                <Select labelId="branch-label" label="branch" value={formData.branch} onChange={handleInputChange} name="branch">
                  <MenuItem value="All">All</MenuItem>
                  {branchList?.map((row) => (
                    <MenuItem key={row.id} value={row.branch}>
                      {row.branch}
                    </MenuItem>
                  ))}
                </Select>
                {fieldErrors.branch && <FormHelperText>{fieldErrors.branch}</FormHelperText>}
              </FormControl>
            </div>
          )}

          {selectedSections.dueDate && (
            <>
              <div className="col-md-3">
                <FormControl fullWidth variant="filled" size="small">
                  <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <DatePicker
                      label="Due Date"
                      value={formData.dueDate ? dayjs(formData.dueDate, 'DD-MM-YYYY') : null}
                      onChange={(date) => handleDateChange('dueDate', date)}
                      slotProps={{
                        textField: { size: 'small', clearable: true, error: fieldErrors.dueDate, helperText: fieldErrors.dueDate }
                      }}
                      format="DD-MM-YYYY"
                    />
                  </LocalizationProvider>
                </FormControl>
              </div>
            </>
          )}

          {selectedSections.slab && (
            <>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 1</span>} name="slab1" size="small" value={formData.slab1} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 2</span>} name="slab2" size="small" value={formData.slab2} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 3</span>} name="slab3" size="small" value={formData.slab3} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 4</span>} name="slab4" size="small" value={formData.slab4} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 5</span>} name="slab5" size="small" value={formData.slab5} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 6</span>} name="slab6" size="small" value={formData.slab6} onChange={handleInputChange} />
                </FormControl>
              </div>
            </>
          )}

          {(selectedSections.partyName || selectedSections.date) && (
            <div className="col-md-3">
              <div className="row d-flex ml">
                <div className="d-flex flex-wrap justify-content-start mb-1 mt-1">
                  <ActionButton title="Search" icon={SearchIcon} onClick={handleSearch} disabled={isLoading} />
                  <ActionButton title="Clear" icon={ClearIcon} onClick={allClearData} />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Search Results Modal */}
        <Dialog
          open={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          fullWidth={true}
          maxWidth="xl"
          PaperProps={{
            sx: {
              height: '80vh',
              maxHeight: '80vh',
              borderRadius: '12px',
              overflow: 'hidden'
            }
          }}
        >
          <DialogTitle
            sx={{
              m: 0,
              p: 0,
              px: 3,
              backgroundColor: '#34449B',
              color: 'white',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}
          >
            <div className="text-xl font-bold">AR Outstanding Report</div>
            <Button
              onClick={() => setIsModalOpen(false)}
              sx={{
                color: 'white',
                minWidth: 'auto',
                padding: '6px'
              }}
            >
              <ClearIcon fontSize="medium" />
            </Button>
          </DialogTitle>

          <DialogContent dividers sx={{ padding: 0 }}>
            <div className="w-full h-full">
              <CommonReportTable
                data={rowData}
                columns={reportColumns}
                fileName={'AP_Outstanding_Report'}
                isListView={true}
                handleDownloadExcel={() => handleDownloadExcel({ logo: listViewData[0]?.companyLogo })}
                handleDownloadPdf={() =>
                  handleDownloadPdf({
                    logo: listViewData[0]?.companyLogo,
                    columns: reportColumns,
                    data: rowData,
                    formData,
                    fileName: 'AR_Outstanding_Report',

                    userName
                  })
                }
                tableOptions={{
                  muiTablePaperProps: {
                    sx: {
                      border: 'none',
                      boxShadow: 'none',
                      borderRadius: '0',
                      height: '100%'
                    }
                  },
                  muiTableContainerProps: {
                    sx: {
                      maxHeight: 'calc(80vh - 132px)',
                      height: '100%'
                    }
                  },
                  muiTableBodyRowProps: ({ row }) => ({
                    sx: {
                      backgroundColor: row.index % 2 ? '#f9f9f9' : '#ffffff',
                      '&:hover': { backgroundColor: '#f0f7ff' }
                    }
                  }),
                  enableStickyHeader: true,
                  muiTableProps: {
                    sx: {
                      borderCollapse: 'collapse',
                      '& .MuiTableCell-root': {
                        border: '1px solid #e0e0e0 !important'
                      }
                    }
                  }
                }}
                headerFields={headerFields}
                // sumFields={['outstanding', 'unadjusted', 'totaldue']}
              />
            </div>
          </DialogContent>
        </Dialog>
        {listView && (
          <div className="mt-4">
            <CommonReportTable
              data={rowData}
              columns={reportColumns}
              fileName={'AP Outstanding Report'}
              isListView={true}
              handleDownloadExcel={() => handleDownloadExcel({ logo: listViewData[0]?.companyLogo })}
              handleDownloadPdf={() =>
                handleDownloadPdf({
                  logo: listViewData[0]?.companyLogo,
                  columns: reportColumns,
                  data: rowData,
                  formData,
                  fileName: 'AR_Outstanding_Report',
                  userName
                })
              }
              tableOptions={{
                ...tableOptions,
                muiTableContainerProps: { sx: { maxHeight: '60vh' } }
              }}
              headerFields={headerFields}
              // sumFields={['amount', 'outstanding', 'totaldue',]}
            />
          </div>
        )}
        {isLoading && (
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              marginTop: '20px',
              width: '100%'
            }}
          >
            <CircularProgress size={40} />
          </div>
        )}
      </div>
    </>
  );
};

export default ArOutstanding;
