import React from 'react';
import {
  FormControlLabel,
  Checkbox,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  FormHelperText,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button
} from '@mui/material';
import { useState, useEffect } from 'react';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider, DatePicker } from '@mui/x-date-pickers';
import ActionButton from 'utils/ActionButton';
import ClearIcon from '@mui/icons-material/Clear';
import SearchIcon from '@mui/icons-material/Search';
import dayjs from 'dayjs';
import apiCalls from 'apicall';
import { showToast } from 'utils/toast-component';
import CommonReportTable from 'utils/CommonReportTable';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { getAllActiveBranches } from 'utils/CommonFunctions';

const ArOutstanding = () => {
  const [orgId, setOrgId] = useState(localStorage.getItem('orgId'));
  const [finYear, setFinYear] = useState(localStorage.getItem('finYear'));
  const [isLoading, setIsLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [partyNameList, setpartyNameList] = useState([]);
  const [fieldErrors, setFieldErrors] = useState({});
  const [rowData, setRowData] = useState([]);
  const [branchList, setbranchList] = useState([]);
  const [listView, setListView] = useState(false);
  const [selectedSections, setSelectedSections] = useState({
    partyName: false,
    date: true,
    slab: false,
    branch: false,
    dueDate: false
  });
  const [headerFields, setHeaderFields] = useState([]);
  const capitalizeHeader = (text) => text.replace(/\b\w/g, (char) => char.toUpperCase());

  const handleChange = (e) => {
    const { name, checked } = e.target;
    setSelectedSections((prevState) => ({
      ...prevState,
      [name]: checked
    }));

    if (name === 'date' && checked) {
      const today = dayjs().format('YYYY-MM-DD');
      setFormData((prev) => ({
        ...prev,
        date: today
      }));
      setFieldErrors((prev) => ({
        ...prev,
        date: ''
      }));
    }
  };

  const [formData, setFormData] = useState({
    partyName: 'All',
    date: dayjs().format('YYYY-MM-DD'),
    dueDate: null,
    branch: 'All',
    slab1: '',
    slab2: '',
    slab3: '',
    slab4: '',
    slab5: '',
    slab6: ''
  });

  const handleDownloadExcel = async () => {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('AR Ageing Report');

    // ====== TITLE ======
    sheet.mergeCells('A1:G1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = 'Accounts Receivable Outstanding Report';
    titleCell.font = {
      size: 18,
      bold: true,
      color: { argb: 'FF34449B' }
    };
    titleCell.alignment = {
      vertical: 'middle',
      horizontal: 'center'
    };

    // ====== HEADER INFO ======
    const headerInfo = [
      ...headerFields,
      { label: 'Generated By', value: localStorage.getItem('userName') || 'Admin' },
      { label: 'Generated On', value: dayjs().format('DD-MM-YYYY HH:mm') }
    ];

    for (let i = 0; i < headerInfo.length; i += 2) {
      const rowIndex = i / 2 + 2;
      const row = sheet.getRow(rowIndex);

      const labelCell1 = row.getCell(1);
      const valueCell1 = row.getCell(2);
      labelCell1.value = headerInfo[i].label + ':';
      labelCell1.font = { bold: true };
      valueCell1.value = headerInfo[i].value;

      if (headerInfo[i + 1]) {
        const labelCell2 = row.getCell(4);
        const valueCell2 = row.getCell(5);
        labelCell2.value = headerInfo[i + 1].label + ':';
        labelCell2.font = { bold: true };
        valueCell2.value = headerInfo[i + 1].value;
      }
    }

    // ====== COLUMN HEADERS ======
    const headers = ['Branch', 'Vendor', 'Credit Days', 'Credit Limit', 'Outstanding', 'Unadjusted', 'Total Due'];
    const headerRow = sheet.addRow(headers);
    headerRow.font = {
      bold: true,
      color: { argb: 'FFFFFFFF' }
    };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF34449B' }
    };
    headerRow.alignment = {
      horizontal: 'center',
      vertical: 'middle'
    };
    headerRow.height = 20;

    headerRow.eachCell((cell) => {
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // ====== DATA ROWS ======
    rowData.forEach((item) => {
      const vendorParts = [item.subledgerCode || '', item.subledgerName || '', item.currency || ''].filter(Boolean).join(' - ');

      const vendorDisplay = item.subledgerName?.toLowerCase().startsWith('total') ? item.subledgerName : vendorParts;

      const row = sheet.addRow([
        item.branch || '-',
        vendorDisplay || '-',
        item.creditDays ?? '',
        item.creditLimit ?? 0,
        item.outstanding ?? 0,
        item.unadjusted ?? 0,
        item.totaldue ?? 0
      ]);

      // Format numeric columns
      [3, 4, 5, 6].forEach((colIdx) => {
        const cell = row.getCell(colIdx + 1);
        if (typeof cell.value === 'number') {
          cell.numFmt = '#,##0.00';
          cell.alignment = { horizontal: 'right' };
        }
      });

      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });

    // ====== COLUMN WIDTHS ======
    sheet.columns = [
      { width: 20 }, // Branch
      { width: 40 }, // Vendor
      { width: 12 }, // Credit Days
      { width: 15 }, // Credit Limit
      { width: 15 }, // Outstanding
      { width: 15 }, // Unadjusted
      { width: 15 } // Total Due
    ];

    // ====== EXPORT FILE ======
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    saveAs(blob, `AR_Outstanding_Report_${dayjs().format('YYYYMMDD_HHmmss')}.xlsx`);
  };

  const handleDateChange = (field, date) => {
    const formattedDate = date ? dayjs(date).format('YYYY-MM-DD') : null;
    setFormData((prevData) => ({ ...prevData, [field]: formattedDate }));
    setFieldErrors((prev) => ({ ...prev, date: '' }));
  };

  const allClearData = () => {
    setFormData({ partyName: 'All', date: dayjs().format('YYYY-MM-DD'), branch: 'ALL' });
    setSelectedSections({ partyName: false, date: true });
    setFieldErrors({});
    setListView(false);
    setRowData([]);
  };

  useEffect(() => {
    getpartyName();
    getAllBranches();
  }, []);

  const getAllBranches = async () => {
    try {
      const branchData = await getAllActiveBranches(orgId);
      setbranchList(branchData);
    } catch (error) {
      console.error('Error fetching country data:', error);
    }
  };

  const getpartyName = async () => {
    try {
      const response = await apiCalls('get', `/taxInvoice/getPartyNameByPartyType?orgId=${orgId}&partyType=customer`);
      setpartyNameList(response.paramObjectsMap.partyMasterVO);
    } catch (error) {
      console.error('Error fetching gate passes:', error);
    }
  };

  const handleSelectPartyName = (e) => {
    const value = e.target.value;
    if (value === 'All') {
      setFormData((prevData) => ({
        ...prevData,
        partyName: 'All'
      }));
    } else {
      const selectedEmp = partyNameList.find((emp) => emp.partyName === value);

      if (selectedEmp) {
        setFormData((prevData) => ({
          ...prevData,
          partyName: selectedEmp.partyName
        }));
      }
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type } = e.target;

    setFieldErrors((prevErrors) => ({
      ...prevErrors,
      [name]: ''
    }));

    // if (name === 'branch') {
    //   if (value === 'All') {
    //     setFormData((prevData) => ({
    //       ...prevData,
    //       branch: 'All'
    //     }));
    //   }
    // }
    let inputValue = value;
    if (type === 'text' || type === 'textarea') {
      inputValue = value.toUpperCase();
    }
    setFormData((prevData) => ({ ...prevData, [name]: inputValue }));
  };

  const handleCheckboxChange = (event) => {
    const { name, checked } = event.target;
    setSelectedSections((prevState) => ({
      ...prevState,
      [name]: checked
    }));
  };

  const formatAmount = (value) => (value !== null && value !== undefined ? new Intl.NumberFormat('en-IN').format(value) : '');

  const reportColumns = [
    {
      accessorKey: 'branch',
      header: 'Branch',
      size: 80,
      Cell: ({ cell }) => <div style={{ textAlign: 'left', padding: '8px' }}>{cell.getValue() || ''}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      header: 'Vendor',
      accessorKey: 'combinedVendorInfo',
      size: 300,
      Cell: ({ row }) => {
        const code = row.original.subledgerCode || '';
        const name = row.original.subledgerName || '';
        const currency = row.original.currency || '';

        if (name.toLowerCase().startsWith('total')) {
          return <div style={{ textAlign: 'left', padding: '8px' }}>{name}</div>;
        }

        const parts = [code, name, currency].filter(Boolean);
        const displayValue = parts.join(' - ');

        return <div style={{ textAlign: 'left', padding: '8px' }}>{displayValue}</div>;
      },
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'creditDays',
      header: 'Credit Days',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'left', padding: '8px' }}>{cell.getValue() || ''}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'creditLimit',
      header: 'Credit Limit',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'outstanding',
      header: 'Outstanding',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'unadjusted',
      header: 'Unadjusted',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    },
    {
      accessorKey: 'totaldue',
      header: 'Total Due',
      size: 100,
      Cell: ({ cell }) => <div style={{ textAlign: 'right', padding: '8px' }}>{formatAmount(cell.getValue())}</div>,
      muiTableHeadCellProps: {
        align: 'center',
        sx: {
          backgroundColor: '#34449B',
          color: 'white',
          fontWeight: 'bold',
          fontSize: '0.875rem',
          padding: '12px 8px'
        }
      },
      muiTableBodyCellProps: {
        sx: {
          padding: '8px',
          backgroundColor: '#ffffff'
        }
      }
    }
  ];

  const handleSearch = async () => {
    if (selectedSections.date && !formData.date) {
      setFieldErrors((prevErrors) => ({
        ...prevErrors,
        date: selectedSections.date && !formData.date ? 'Date is required' : ''
      }));
      return;
    } else {
      setIsLoading(true);
      try {
        let response;
        if (formData.dueDate) {
          response = await apiCalls(
            'get',
            `/arapAdjustments/GetArapAdjustments?Asondate=${formData.date}&branch=${formData.branch}&orgId=${orgId}&partyname=${formData.partyName}&pdate=${formData.dueDate}`
          );
        } else {
          response = await apiCalls(
            'get',
            `/arapAdjustments/GetArapAdjustments?Asondate=${formData.date}&partyname=${formData.partyName}&orgId=${orgId}&branch=${formData.branch}`
          );
        }
        if (response.status === true) {
          setRowData(response.paramObjectsMap.mapp);

          const headers = [
            // {
            //   // Combined date range value without a label
            //   value: formData.fromDate && formData.toDate
            //     ? `${dayjs(formData.fromDate).format('DD-MM-YYYY')} to ${dayjs(formData.toDate).format('DD-MM-YYYY')}`
            //     : ''
            // },
            {
              label: 'As On Date',
              value: formData.date
            },
            {
              label: 'Party Name',
              value: formData.partyName !== 'All' ? formData.partyName : 'All'
            },
            {
              label: 'Branch',
              value: formData.branch !== 'All' ? formData.branch : 'All'
            }
          ];

          setHeaderFields(headers);
          setIsLoading(false);
          setListView(true);
          setIsModalOpen(true);
        } else {
          showToast('error', response.paramObjectsMap.mapp.errorMessage || 'Report Fetch failed');
          setIsLoading(false);
        }
      } catch (error) {
        console.error('Error:', error);
        showToast('error', 'Report Fetch failed');
        setIsLoading(false);
      } finally {
        setIsLoading(false);
      }
    }
  };

  const tableOptions = {
    muiTablePaperProps: {
      sx: {
        border: '1px solid #e0e0e0',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
        borderRadius: '8px',
        overflow: 'hidden'
      }
    },
    muiTableContainerProps: {
      sx: { maxHeight: '70vh' }
    },
    muiTableBodyRowProps: ({ row }) => ({
      sx: {
        backgroundColor: row.index % 2 ? '#f9f9f9' : '#ffffff',
        '&:hover': { backgroundColor: '#f0f7ff' }
      }
    }),
    enableStickyHeader: true,
    muiTableProps: {
      sx: {
        borderCollapse: 'collapse',
        '& .MuiTableCell-root': {
          border: '1px solid #e0e0e0 !important'
        }
      }
    }
  };

  return (
    <>
      <div className="card w-full p-6 bg-base-100 shadow-xl" style={{ padding: '20px', borderRadius: '10px' }}>
        <div className="row">
          <div className="row">
            <div className="col-md-2  mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.date} onChange={handleChange} name="date" color="secondary" />}
                label="Date"
              />
            </div>

            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.partyName} onChange={handleChange} name="partyName" color="secondary" />}
                label="Party Name"
              />
            </div>
            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.branch} onChange={handleCheckboxChange} name="branch" color="secondary" />}
                label="Branch"
              />
            </div>
            <div className="col-md-2 mb-3">
              <FormControlLabel
                control={<Checkbox checked={selectedSections.dueDate} onChange={handleCheckboxChange} name="dueDate" color="secondary" />}
                label="Due Date"
              />
            </div>
          </div>

          {selectedSections.date && (
            <div className="col-md-3">
              <FormControl fullWidth variant="filled" size="small">
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                  <DatePicker
                    label="As on Date"
                    format="DD-MM-YYYY"
                    onChange={(date) => handleDateChange('date', date)}
                    value={formData.date ? dayjs(formData.date, 'YYYY-MM-DD') : null}
                    slotProps={{
                      textField: {
                        size: 'small',
                        clearable: true,
                        error: !!fieldErrors.date,
                        helperText: fieldErrors.date
                      }
                    }}
                  />
                </LocalizationProvider>
              </FormControl>
            </div>
          )}

          {selectedSections.partyName && (
            <div className="col-md-3">
              <FormControl size="small" variant="outlined" fullWidth error={!!fieldErrors.partyName}>
                <InputLabel id="partyName-label">Party Name</InputLabel>
                <Select
                  labelId="partyName-label"
                  label="Party Name"
                  name="partyName"
                  value={formData.partyName}
                  onChange={handleSelectPartyName}
                  onBlur={() => {
                    if (!formData.partyName) {
                      setFieldErrors((prev) => ({
                        ...prev,
                        partyName: 'Party Name is required'
                      }));
                    }
                  }}
                >
                  <MenuItem value="All">All</MenuItem>
                  {partyNameList?.map((row) => (
                    <MenuItem key={row.id} value={row.partyName}>
                      {row.partyName}
                    </MenuItem>
                  ))}
                </Select>
                {fieldErrors.partyName && <FormHelperText>{fieldErrors.partyName}</FormHelperText>}
              </FormControl>
            </div>
          )}

          {selectedSections.branch && (
            <div className="col-md-3">
              <FormControl size="small" variant="outlined" fullWidth error={!!fieldErrors.branch}>
                <InputLabel id="branch-label">Branch</InputLabel>
                <Select labelId="branch-label" label="branch" value={formData.branch} onChange={handleInputChange} name="branch">
                  <MenuItem value="All">All</MenuItem>
                  {branchList?.map((row) => (
                    <MenuItem key={row.id} value={row.branch}>
                      {row.branch}
                    </MenuItem>
                  ))}
                </Select>
                {fieldErrors.branch && <FormHelperText>{fieldErrors.branch}</FormHelperText>}
              </FormControl>
            </div>
          )}

          {selectedSections.dueDate && (
            <>
              <div className="col-md-3">
                <FormControl fullWidth variant="filled" size="small">
                  <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <DatePicker
                      label="Due Date"
                      value={formData.dueDate ? dayjs(formData.dueDate, 'YYYY-MM-DD') : null}
                      onChange={(date) => handleDateChange('dueDate', date)}
                      slotProps={{
                        textField: { size: 'small', clearable: true, error: fieldErrors.dueDate, helperText: fieldErrors.dueDate }
                      }}
                      format="DD-MM-YYYY"
                    />
                  </LocalizationProvider>
                </FormControl>
              </div>
            </>
          )}

          {selectedSections.slab && (
            <>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 1</span>} name="slab1" size="small" value={formData.slab1} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 2</span>} name="slab2" size="small" value={formData.slab2} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 3</span>} name="slab3" size="small" value={formData.slab3} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 4</span>} name="slab4" size="small" value={formData.slab4} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 5</span>} name="slab5" size="small" value={formData.slab5} onChange={handleInputChange} />
                </FormControl>
              </div>
              <div className="col-md-3">
                <FormControl fullWidth size="small">
                  <TextField label={<span>Slab 6</span>} name="slab6" size="small" value={formData.slab6} onChange={handleInputChange} />
                </FormControl>
              </div>
            </>
          )}

          {(selectedSections.partyName || selectedSections.date) && (
            <div className="col-md-3">
              <div className="row d-flex ml">
                <div className="d-flex flex-wrap justify-content-start mb-1 mt-1">
                  <ActionButton title="Search" icon={SearchIcon} onClick={handleSearch} disabled={isLoading} />
                  <ActionButton title="Clear" icon={ClearIcon} onClick={allClearData} />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Search Results Modal */}
        <Dialog
          open={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          fullWidth={true}
          maxWidth="xl"
          PaperProps={{
            sx: {
              height: '80vh',
              maxHeight: '80vh',
              borderRadius: '12px',
              overflow: 'hidden'
            }
          }}
        >
          <DialogTitle
            sx={{
              m: 0,
              p: 0,
              px: 3,
              backgroundColor: '#34449B',
              color: 'white',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}
          >
            <div className="text-xl font-bold">AR Outstanding Report</div>
            <Button
              onClick={() => setIsModalOpen(false)}
              sx={{
                color: 'white',
                minWidth: 'auto',
                padding: '6px'
              }}
            >
              <ClearIcon fontSize="medium" />
            </Button>
          </DialogTitle>

          <DialogContent dividers sx={{ padding: 0 }}>
            <div className="w-full h-full">
              <CommonReportTable
                data={rowData}
                columns={reportColumns}
                fileName={'AP_Outstanding_Report'}
                isListView={true}
                handleDownloadExcel={handleDownloadExcel}
                tableOptions={{
                  muiTablePaperProps: {
                    sx: {
                      border: 'none',
                      boxShadow: 'none',
                      borderRadius: '0',
                      height: '100%'
                    }
                  },
                  muiTableContainerProps: {
                    sx: {
                      maxHeight: 'calc(80vh - 132px)',
                      height: '100%'
                    }
                  },
                  muiTableBodyRowProps: ({ row }) => ({
                    sx: {
                      backgroundColor: row.index % 2 ? '#f9f9f9' : '#ffffff',
                      '&:hover': { backgroundColor: '#f0f7ff' }
                    }
                  }),
                  enableStickyHeader: true,
                  muiTableProps: {
                    sx: {
                      borderCollapse: 'collapse',
                      '& .MuiTableCell-root': {
                        border: '1px solid #e0e0e0 !important'
                      }
                    }
                  }
                }}
                headerFields={headerFields}
                // sumFields={['outstanding', 'unadjusted', 'totaldue']}
              />
            </div>
          </DialogContent>
        </Dialog>
        {listView && (
          <div className="mt-4">
            <CommonReportTable
              data={rowData}
              columns={reportColumns}
              fileName={'AP Outstanding Report'}
              isListView={true}
              handleDownloadExcel={handleDownloadExcel}
              tableOptions={{
                ...tableOptions,
                muiTableContainerProps: { sx: { maxHeight: '60vh' } }
              }}
              headerFields={headerFields}
              // sumFields={['amount', 'outstanding', 'totaldue',]}
            />
          </div>
        )}
      </div>
    </>
  );
};

export default ArOutstanding;
